language: go
before_install:
- pushd $HOME
- wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip
- unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip
- cd google_appengine
- export GAE=$(pwd)
- popd
install:
- cd $TRAVIS_BUILD_DIR
- export GOPATH=$TRAVIS_BUILD_DIR
- export GOHOME=$GAE
- export PATH=$GAE:$PATH
- which go
- go env
script:
- go test -v ./...

