application: bulktracker
version: v0
runtime: go
api_version: go1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static
- url: /mock
  static_dir: mock
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: _go_app

nobuild_files: (bulk|dsbatch|json)/
