application: bulktracker
version: v0
runtime: go
api_version: go1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static
- url: /mock
  static_dir: mock
- url: /images
  static_dir: images
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /pkgresults.*
  static_files: static/pkgresults.html
  upload: static/pkgresults.html
- url: /.*
  script: _go_app

nobuild_files: (bulk|data|dsbatch|ingest|json|templates)/
