runtime: go120

handlers:
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: auto

nobuild_files: (bulk|templates|testing)/
