// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package ddao

import (
	"context"
	"database/sql"
	"time"
)

const deleteAllForBuild = `-- name: DeleteAllForBuild :exec
DELETE from results
WHERE build_id = ?
`

func (q *Queries) DeleteAllForBuild(ctx context.Context, buildID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteAllForBuild, buildID)
	return err
}

const getAllPkgResults = `-- name: GetAllPkgResults :many
SELECT r.result_id, r.pkg_name, COALESCE(m.pkg_maintainer, '') AS pkg_maintainer, r.build_status, r.breaks, b.build_id, b.platform, b.build_ts, b.branch, b.compiler, b.build_user
FROM results r
JOIN builds b ON (r.build_id == b.build_id)
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
WHERE r.pkg_id == ?
ORDER BY b.build_ts DESC
`

type GetAllPkgResultsRow struct {
	ResultID      int64
	PkgName       string
	PkgMaintainer string
	BuildStatus   int64
	Breaks        int64
	BuildID       int64
	Platform      string
	BuildTs       time.Time
	Branch        string
	Compiler      string
	BuildUser     string
}

func (q *Queries) GetAllPkgResults(ctx context.Context, pkgID sql.NullInt64) ([]GetAllPkgResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPkgResults, pkgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPkgResultsRow
	for rows.Next() {
		var i GetAllPkgResultsRow
		if err := rows.Scan(
			&i.ResultID,
			&i.PkgName,
			&i.PkgMaintainer,
			&i.BuildStatus,
			&i.Breaks,
			&i.BuildID,
			&i.Platform,
			&i.BuildTs,
			&i.Branch,
			&i.Compiler,
			&i.BuildUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuild = `-- name: GetBuild :one
SELECT build_id, platform, build_ts, branch, compiler, build_user, report_url, num_ok, num_prefailed, num_failed, num_indirect_failed, num_indirect_prefailed, last_error FROM builds
WHERE build_id = ?
`

func (q *Queries) GetBuild(ctx context.Context, buildID int64) (Build, error) {
	row := q.db.QueryRowContext(ctx, getBuild, buildID)
	var i Build
	err := row.Scan(
		&i.BuildID,
		&i.Platform,
		&i.BuildTs,
		&i.Branch,
		&i.Compiler,
		&i.BuildUser,
		&i.ReportUrl,
		&i.NumOk,
		&i.NumPrefailed,
		&i.NumFailed,
		&i.NumIndirectFailed,
		&i.NumIndirectPrefailed,
		&i.LastError,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT DISTINCT category
FROM pkgs
ORDER BY category
`

func (q *Queries) GetCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBuildsPerPlatform = `-- name: GetLatestBuildsPerPlatform :many

SELECT build_id, platform, build_ts, branch, compiler, build_user, report_url, num_ok, num_prefailed, num_failed, num_indirect_failed, num_indirect_prefailed, last_error FROM builds
WHERE build_id IN (
	SELECT DISTINCT
	MAX(build_id) OVER (PARTITION BY platform, branch, compiler, build_user)
	FROM builds
) 
ORDER BY build_ts DESC
LIMIT 1000
`

// This relies on the fact that IDs are monotonically increasing, so a newer
// build will have a higher ID. There is probably a cleaner way.
func (q *Queries) GetLatestBuildsPerPlatform(ctx context.Context) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, getLatestBuildsPerPlatform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.BuildID,
			&i.Platform,
			&i.BuildTs,
			&i.Branch,
			&i.Compiler,
			&i.BuildUser,
			&i.ReportUrl,
			&i.NumOk,
			&i.NumPrefailed,
			&i.NumFailed,
			&i.NumIndirectFailed,
			&i.NumIndirectPrefailed,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaintainerID = `-- name: GetMaintainerID :one
SELECT maintainer_id FROM maintainers
WHERE pkg_maintainer == ?
`

func (q *Queries) GetMaintainerID(ctx context.Context, pkgMaintainer string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaintainerID, pkgMaintainer)
	var maintainer_id int64
	err := row.Scan(&maintainer_id)
	return maintainer_id, err
}

const getPkgID = `-- name: GetPkgID :one
SELECT pkg_id FROM pkgs
WHERE category == ? and dir == ?
`

type GetPkgIDParams struct {
	Category string
	Dir      string
}

func (q *Queries) GetPkgID(ctx context.Context, arg GetPkgIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPkgID, arg.Category, arg.Dir)
	var pkg_id int64
	err := row.Scan(&pkg_id)
	return pkg_id, err
}

const getPkgsBreakingMostOthers = `-- name: GetPkgsBreakingMostOthers :many
SELECT
	r.result_id,
	(p.category || p.dir) AS pkg_path,
	r.pkg_name,
	COALESCE(m.pkg_maintainer, '') AS pkg_maintainer,
	r.build_status,
	r.failed_deps,
	r.breaks
FROM results r
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
JOIN pkgs p ON (r.pkg_id == p.pkg_id)
WHERE r.build_id == ? AND r.build_status > 0
ORDER BY r.breaks DESC
LIMIT 100
`

type GetPkgsBreakingMostOthersRow struct {
	ResultID      int64
	PkgPath       interface{}
	PkgName       string
	PkgMaintainer string
	BuildStatus   int64
	FailedDeps    string
	Breaks        int64
}

func (q *Queries) GetPkgsBreakingMostOthers(ctx context.Context, buildID sql.NullInt64) ([]GetPkgsBreakingMostOthersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPkgsBreakingMostOthers, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPkgsBreakingMostOthersRow
	for rows.Next() {
		var i GetPkgsBreakingMostOthersRow
		if err := rows.Scan(
			&i.ResultID,
			&i.PkgPath,
			&i.PkgName,
			&i.PkgMaintainer,
			&i.BuildStatus,
			&i.FailedDeps,
			&i.Breaks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPkgsInCategory = `-- name: GetPkgsInCategory :many
SELECT DISTINCT dir
FROM pkgs
WHERE category = ?
ORDER BY dir
`

func (q *Queries) GetPkgsInCategory(ctx context.Context, category string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPkgsInCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dir string
		if err := rows.Scan(&dir); err != nil {
			return nil, err
		}
		items = append(items, dir)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultsInCategory = `-- name: GetResultsInCategory :many
SELECT r.result_id, r.build_id, r.pkg_id, r.pkg_name, r.build_status, r.failed_deps, r.breaks, r.maintainer_id, p.pkg_id, p.category, p.dir, COALESCE(m.pkg_maintainer, '') AS pkg_maintainer
FROM results r
JOIN pkgs p ON (r.pkg_id == p.pkg_id)
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
WHERE p.category == ? AND r.build_id == ?
`

type GetResultsInCategoryParams struct {
	Category string
	BuildID  sql.NullInt64
}

type GetResultsInCategoryRow struct {
	ResultID      int64
	BuildID       sql.NullInt64
	PkgID         sql.NullInt64
	PkgName       string
	BuildStatus   int64
	FailedDeps    string
	Breaks        int64
	MaintainerID  sql.NullInt64
	PkgID_2       int64
	Category      string
	Dir           string
	PkgMaintainer string
}

func (q *Queries) GetResultsInCategory(ctx context.Context, arg GetResultsInCategoryParams) ([]GetResultsInCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getResultsInCategory, arg.Category, arg.BuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsInCategoryRow
	for rows.Next() {
		var i GetResultsInCategoryRow
		if err := rows.Scan(
			&i.ResultID,
			&i.BuildID,
			&i.PkgID,
			&i.PkgName,
			&i.BuildStatus,
			&i.FailedDeps,
			&i.Breaks,
			&i.MaintainerID,
			&i.PkgID_2,
			&i.Category,
			&i.Dir,
			&i.PkgMaintainer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentinelStatus = `-- name: GetSentinelStatus :many

SELECT result_id, build_id, pkg_id, pkg_name, build_status, failed_deps, breaks, maintainer_id
FROM results
WHERE build_id == ? AND pkg_id IN (
	SELECT pkg_id
	FROM pkgs
	WHERE dir LIKE 'bulk-test-%'
)
`

// Get the status and failed dependencies of the sentinel packages
// (bulk-test-*).
func (q *Queries) GetSentinelStatus(ctx context.Context, buildID sql.NullInt64) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, getSentinelStatus, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ResultID,
			&i.BuildID,
			&i.PkgID,
			&i.PkgName,
			&i.BuildStatus,
			&i.FailedDeps,
			&i.Breaks,
			&i.MaintainerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleResult = `-- name: GetSingleResult :one
SELECT
	r.result_id,
	r.pkg_name,
	COALESCE(m.pkg_maintainer, '') AS pkg_maintainer,
	r.build_status,
	r.failed_deps,
	r.breaks,
	p.category,
	p.dir,
	b.build_id,
	b.platform,
	b.build_ts,
	b.branch,
	b.compiler,
	b.build_user,
	b.report_url
FROM results r
JOIN builds b ON (r.build_id == b.build_id)
JOIN pkgs p ON (r.pkg_id == p.pkg_id)
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
WHERE r.result_id == ?
`

type GetSingleResultRow struct {
	ResultID      int64
	PkgName       string
	PkgMaintainer string
	BuildStatus   int64
	FailedDeps    string
	Breaks        int64
	Category      string
	Dir           string
	BuildID       int64
	Platform      string
	BuildTs       time.Time
	Branch        string
	Compiler      string
	BuildUser     string
	ReportUrl     string
}

func (q *Queries) GetSingleResult(ctx context.Context, resultID int64) (GetSingleResultRow, error) {
	row := q.db.QueryRowContext(ctx, getSingleResult, resultID)
	var i GetSingleResultRow
	err := row.Scan(
		&i.ResultID,
		&i.PkgName,
		&i.PkgMaintainer,
		&i.BuildStatus,
		&i.FailedDeps,
		&i.Breaks,
		&i.Category,
		&i.Dir,
		&i.BuildID,
		&i.Platform,
		&i.BuildTs,
		&i.Branch,
		&i.Compiler,
		&i.BuildUser,
		&i.ReportUrl,
	)
	return i, err
}

const getSingleResultByPkgName = `-- name: GetSingleResultByPkgName :one
SELECT
	r.result_id,
	r.pkg_name,
	COALESCE(m.pkg_maintainer, '') AS pkg_maintainer,
	r.build_status,
	r.failed_deps,
	r.breaks,
	p.category,
	p.dir
FROM results r
JOIN pkgs p ON (r.pkg_id == p.pkg_id)
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
WHERE r.build_id == ? AND r.pkg_name == ?
`

type GetSingleResultByPkgNameParams struct {
	BuildID sql.NullInt64
	PkgName string
}

type GetSingleResultByPkgNameRow struct {
	ResultID      int64
	PkgName       string
	PkgMaintainer string
	BuildStatus   int64
	FailedDeps    string
	Breaks        int64
	Category      string
	Dir           string
}

func (q *Queries) GetSingleResultByPkgName(ctx context.Context, arg GetSingleResultByPkgNameParams) (GetSingleResultByPkgNameRow, error) {
	row := q.db.QueryRowContext(ctx, getSingleResultByPkgName, arg.BuildID, arg.PkgName)
	var i GetSingleResultByPkgNameRow
	err := row.Scan(
		&i.ResultID,
		&i.PkgName,
		&i.PkgMaintainer,
		&i.BuildStatus,
		&i.FailedDeps,
		&i.Breaks,
		&i.Category,
		&i.Dir,
	)
	return i, err
}

const getSingleResultIDByPkgName = `-- name: GetSingleResultIDByPkgName :one
SELECT result_id
FROM results
WHERE build_id == ? and pkg_name == ?
`

type GetSingleResultIDByPkgNameParams struct {
	BuildID sql.NullInt64
	PkgName string
}

func (q *Queries) GetSingleResultIDByPkgName(ctx context.Context, arg GetSingleResultIDByPkgNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSingleResultIDByPkgName, arg.BuildID, arg.PkgName)
	var result_id int64
	err := row.Scan(&result_id)
	return result_id, err
}

const putBuild = `-- name: PutBuild :one

INSERT INTO builds
(platform, build_ts, branch, compiler, build_user, report_url, num_ok,
	num_prefailed, num_failed, num_indirect_failed, num_indirect_prefailed)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING build_id
`

type PutBuildParams struct {
	Platform             string
	BuildTs              time.Time
	Branch               string
	Compiler             string
	BuildUser            string
	ReportUrl            string
	NumOk                int64
	NumPrefailed         int64
	NumFailed            int64
	NumIndirectFailed    int64
	NumIndirectPrefailed int64
}

// PutBuild writes the Build record to the DB and returns the ID.
func (q *Queries) PutBuild(ctx context.Context, arg PutBuildParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, putBuild,
		arg.Platform,
		arg.BuildTs,
		arg.Branch,
		arg.Compiler,
		arg.BuildUser,
		arg.ReportUrl,
		arg.NumOk,
		arg.NumPrefailed,
		arg.NumFailed,
		arg.NumIndirectFailed,
		arg.NumIndirectPrefailed,
	)
	var build_id int64
	err := row.Scan(&build_id)
	return build_id, err
}

const putMaintainer = `-- name: PutMaintainer :exec
INSERT OR IGNORE INTO maintainers
(pkg_maintainer)
VALUES (?)
`

func (q *Queries) PutMaintainer(ctx context.Context, pkgMaintainer string) error {
	_, err := q.db.ExecContext(ctx, putMaintainer, pkgMaintainer)
	return err
}

const putPkg = `-- name: PutPkg :exec
INSERT OR IGNORE INTO pkgs
(category, dir)
VALUES (?, ?)
`

type PutPkgParams struct {
	Category string
	Dir      string
}

func (q *Queries) PutPkg(ctx context.Context, arg PutPkgParams) error {
	_, err := q.db.ExecContext(ctx, putPkg, arg.Category, arg.Dir)
	return err
}

const putResult = `-- name: PutResult :exec
INSERT INTO results
(build_id, pkg_id, pkg_name, build_status, breaks, failed_deps, maintainer_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type PutResultParams struct {
	BuildID      sql.NullInt64
	PkgID        sql.NullInt64
	PkgName      string
	BuildStatus  int64
	Breaks       int64
	FailedDeps   string
	MaintainerID sql.NullInt64
}

func (q *Queries) PutResult(ctx context.Context, arg PutResultParams) error {
	_, err := q.db.ExecContext(ctx, putResult,
		arg.BuildID,
		arg.PkgID,
		arg.PkgName,
		arg.BuildStatus,
		arg.Breaks,
		arg.FailedDeps,
		arg.MaintainerID,
	)
	return err
}

const resultCount = `-- name: ResultCount :one

SELECT count(*)
FROM results r
WHERE r.build_id = ?
`

// ResultCount returns the number of result records for a given build.
func (q *Queries) ResultCount(ctx context.Context, buildID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, resultCount, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setBuildLastError = `-- name: SetBuildLastError :exec

UPDATE builds
SET last_error = ?
WHERE build_id = ?
`

type SetBuildLastErrorParams struct {
	LastError sql.NullString
	BuildID   int64
}

// SetBuildLastError sets the last_error column on a given build.
func (q *Queries) SetBuildLastError(ctx context.Context, arg SetBuildLastErrorParams) error {
	_, err := q.db.ExecContext(ctx, setBuildLastError, arg.LastError, arg.BuildID)
	return err
}

const deleteBuild = `-- name: deleteBuild :exec
DELETE from builds
WHERE build_id = ?
`

func (q *Queries) deleteBuild(ctx context.Context, buildID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBuild, buildID)
	return err
}

const getAllPkgsMatching = `-- name: getAllPkgsMatching :many
SELECT pkgpath
FROM pkgpaths
WHERE pkgpath LIKE ?1
ORDER BY pkgpath
`

func (q *Queries) getAllPkgsMatching(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllPkgsMatching, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pkgpath string
		if err := rows.Scan(&pkgpath); err != nil {
			return nil, err
		}
		items = append(items, pkgpath)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBuilds = `-- name: getLatestBuilds :many
SELECT build_id, platform, build_ts, branch, compiler, build_user, report_url, num_ok, num_prefailed, num_failed, num_indirect_failed, num_indirect_prefailed, last_error FROM builds
ORDER BY build_ts DESC
LIMIT 1000
`

func (q *Queries) getLatestBuilds(ctx context.Context) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, getLatestBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.BuildID,
			&i.Platform,
			&i.BuildTs,
			&i.Branch,
			&i.Compiler,
			&i.BuildUser,
			&i.ReportUrl,
			&i.NumOk,
			&i.NumPrefailed,
			&i.NumFailed,
			&i.NumIndirectFailed,
			&i.NumIndirectPrefailed,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPkgsBrokenBy = `-- name: getPkgsBrokenBy :many
SELECT
	r.result_id,
	(p.category || p.dir) AS pkg_path,
	r.pkg_name,
	COALESCE(m.pkg_maintainer, '') AS pkg_maintainer,
	r.build_status,
	r.failed_deps,
	r.breaks

FROM results r
LEFT JOIN maintainers m ON (r.maintainer_id == m.maintainer_id)
JOIN pkgs p ON (r.pkg_id == p.pkg_id)
WHERE r.build_id = ? AND
	r.failed_deps LIKE ?
`

type getPkgsBrokenByParams struct {
	BuildID    sql.NullInt64
	FailedDeps string
}

type getPkgsBrokenByRow struct {
	ResultID      int64
	PkgPath       interface{}
	PkgName       string
	PkgMaintainer string
	BuildStatus   int64
	FailedDeps    string
	Breaks        int64
}

func (q *Queries) getPkgsBrokenBy(ctx context.Context, arg getPkgsBrokenByParams) ([]getPkgsBrokenByRow, error) {
	rows, err := q.db.QueryContext(ctx, getPkgsBrokenBy, arg.BuildID, arg.FailedDeps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []getPkgsBrokenByRow
	for rows.Next() {
		var i getPkgsBrokenByRow
		if err := rows.Scan(
			&i.ResultID,
			&i.PkgPath,
			&i.PkgName,
			&i.PkgMaintainer,
			&i.BuildStatus,
			&i.FailedDeps,
			&i.Breaks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
